" Pathogen setup
execute pathogen#infect()
syntax on
filetype plugin indent on

" Tab setup
set tabstop=4
set softtabstop=4
set expandtab
set colorcolumn=80

" UI preferences
colorscheme sierra
set number
set showcmd
set cursorcolumn
set cursorline
filetype indent on

" Syntastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Nerdtree config
let NERDTreeMinimalUI = 1
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-n> :NERDTreeToggle<CR>

" Key bindings
nnoremap j gj
nnoremap k gk
